### ISSUE TITLE
Fix frequent logouts

### ISSUE THREAD

**Issue by saschaishikawa** [zooniverse/old-weather#114]
Users get logged out when the bearer token expires (~2hr). A fix would be to implement a method to refresh bearer tokens once expired.

**Comment by camallen** [comment]
@saschaishikawa a solution for this was implemented in the panoptes-client via https://github.com/zooniverse/panoptes-javascript-client/pull/45

the problem is that web apps can't secure a secret and have to use the implicit grant, that in turn can't use refresh tokens.
