### ISSUE TITLE
Styling: transcription box

### ISSUE THREAD

**Issue by perry** [zooniverse/old-weather#29]
![](http://i.imgur.com/rlrt0BB.png)

**Comment by rogerhutchings** [comment]
#45

**Comment by rogerhutchings** [comment]
I tried to create a context-sensitive input box for lat / longs, but things are a bit too tightly coupled to easily allow it (even with `NgModelController`). Progress is in the [input](https://github.com/zooniverse/old-weather/tree/input) branch.

I've added in the common keys instead via ef111f6bccc773f3b206350e15370557c3afed64.
