### ISSUE TITLE
Process scanned log books

### ISSUE THREAD

**Issue by perry** [zooniverse/old-weather#35]
There are approx. 330k pages that need to be processed.

In my testing, the following command gave great results splitting pages. It first removes the black background from the images (adjust the fuzz parameter, if there is extra noise obstructing), then splits the page down the middle, finally resizing and adjusting quality. This should ideally be run on a dedicated box.

`convert input -fuzz 57% -trim +repage -crop 50%x100% +repage -resize 1500 -quality 50% output`

There is a 2TB drive sent from Gina at the archives in DC, which contains all data and metadata. I have left this with @rogerhutchings, we need to ship this back to Gina when finished.

**Comment by adammcmaster** [comment]
I've split all the double page images, and I'm starting to upload the whole set of data to S3 ready to be added to Panoptes. There were ~28,000 images that couldn't be split. Mostly these seem to be ones where the original file is corrupted or there isn't a page on the left hand side.

We'll do any further processing in EC2 as part of #51.
