### ISSUE TITLE
What does the 'Toggle Guides' button do?

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/old-weather#39]
It just seems to add two black lines to the screen. Not clear what they  are for.

![image](https://cloud.githubusercontent.com/assets/5321335/9135615/53303d64-3d07-11e5-88a1-0daac70a05e8.png)

**Comment by rogerhutchings** [comment]
I remember talking with Perry about aligning the subject to these to make sure the header cell annotations etc all lined up from page to page. I don't think the kind of fine rotation control for this is there though.

**Comment by mrniaboc** [comment]
Hmmm, I think we need to make it clear to the user what they are for.

**Comment by rogerhutchings** [comment]
Removed, probably won't be added back.
