### ISSUE TITLE
Rectangle marking tool behaves weirdly on FF

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/old-weather#4]
I noticed this while bugfixing Transcribe - clicking and dragging on the image element produces the copy image behaviour. Adding `event.preventDefault();` to [svg-drawing-factory-service.js](https://github.com/perry/old-weather/blob/master/app/modules/svg/scripts/svg-drawing-factory-service.js#L49) should stop it.

**Comment by perry** [comment]
Ta :-)
