### ISSUE TITLE
People don't like the separation of the annotation and transcription tasks

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/old-weather#41]
A lot of the feedback from the beta is suggestion people would rather transcribe the page they have just annotated, rather than do a bunch of annotation tasks followed by a bunch of transcription tasks.

**Comment by rogerhutchings** [comment]
What about being offered an option to go and transcribe stuff after you've finished annotating? They're still separate, but you can complete a page yourself that way.

**Comment by mrniaboc** [comment]
I think that would be much more popular, yes.

**Comment by rogerhutchings** [comment]
![screen shot 2015-08-17 at 12 43 30](https://cloud.githubusercontent.com/assets/2725841/9304210/8b9d8e62-44dd-11e5-9675-6acdb1fd0db5.png)

**Comment by rogerhutchings** [comment]
Okay, you can now start transcribing a page after you've annotated it. I can't guarantee it'll be the same page, because the user may have annotated other pages before the current one, but it's close enough.
