### ISSUE TITLE
Choose which sets to upload for launch

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/old-weather#50]
- There are around 330,000 raw subjects, and at a guess, around 650-700 sets. 
- Each set is a voyage, and a ship has multiple voyages. Each voyage is represented individually on OW, so there's `Ammen (1945)`, `Ammen (1960)` etc.
- We don't need this many sets for launch; given that each set is around 500 pages, I'd be happy with 20-30.

@chrislintott / @mrniaboc  - will Phillip be happy with a subset around that size for launch? After talking to @camallen and @astopy, that's definitely the preferred option.

Related to #35

**Comment by chrislintott** [comment]
I think that’s ok - ping him and ask?

Chris

**Comment by rogerhutchings** [comment]
Done, will update the issue when I hear back

**Comment by rogerhutchings** [comment]
That's fine with Philip - we've decided to do the Navy and Coast & Geodetic Survey ships in "The Arctic Frontier" group to begin with.
