### ISSUE TITLE
Moving OW forum to Talk

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/old-weather#65]
Hi @mrniaboc. I don't know if you ever talked about this with Perry, but it's probably a good idea to move the OW forum onto Talk. What do you reckon? Can we get a couple of admins to rescue the more important threads / write something up from them and post them to new Talk?

**Comment by mrniaboc** [comment]
I think it would be great for the OW forum to be transferred to Talk, but how easy will it be to set up new Talk on the new OW?

**Comment by philip-brohan** [comment]
We've talked about this again and again over the last couple of years - it will be hard - there is a lot of data and functionality in the old forum which will need to be preserved. Please check with the oW forum mods for more on this.

**Comment by chrissnyder** [comment]
This general process is ongoing. Janet and the mod team have been doing a great job of setting up the new Talk. The form itself will remain for a long time, especially as it contains a huge amount of archival material.
