### ISSUE TITLE
Grammar correction on front page

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/old-weather#71]
The message at the top of http://www.oldweather.org/ should read:

New site! Visit Old Weather: Whaling for **ships'** logs from whaling ships in the **Arctic**.

**Comment by Caro601** [comment]
And the message on http://whaling.oldweather.org/#/ should read:
Check out other Old **Weather** projects!

**Comment by rogerhutchings** [comment]
wrong repo
