### ISSUE TITLE
Test in IE11+

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/old-weather#73]
@srallen Hate to dump this on you, but could you do the gamut of IE testing on the new Old Weather?

I only have a little bit of info on what to target, but here's a bit that Kevin Wood ran into:

> I was able to annotate (mark) in IE but would not load the transcribe function, and then lost the path and previous work. 

Will add other specific problems as soon as I learn about them.

**Comment by srallen** [comment]
@rogerhutchings, I'm not getting an console errors with the above reported bug in either IE or Edge. What's happening is that the annotation interface isn't getting its state updated to being loaded after the subject image source is loaded. What I'm seeing in F12 dev tools in Edge:

![screen shot 2015-10-27 at 9 40 18 am](https://cloud.githubusercontent.com/assets/5016731/10761898/70cc8f02-7c91-11e5-8a8c-d558dbbe6a76.png)

I'll keep working on this, but wanted to give you a heads up in case you know what to change and it's an easy fix in Angular. Maybe a polyfill is needed?

**Comment by srallen** [comment]
Just as a follow up, it looks like something is going on with ng-load calling the onload event on the svg image in IE/Edge.

**Comment by rogerhutchings** [comment]
I found this one as well. I found that in practice, calling the scope's `subjectLoaded` method in the promise chain just worked :/ 

I also found that there's an issue with drawing on the SVG - changing up the annotations directive to include `replace: true` fixed it.

I'm getting a whole IE + Angular + SVG doesn't mix vibe from this...

**Comment by srallen** [comment]
Hmm... I don't know too much about angular, but I've been playing around with using ng-init and also came across this discussion in the angular repo, but I dunno if it's helpful here yet: https://github.com/angular/angular.js/issues/12493

I agree. It generally seems unstable in IE/Edge.

**Comment by rogerhutchings** [comment]
Ah - I think I know why. `ng-load` is waiting for `load`, in IE it's called `SVGload`

https://msdn.microsoft.com/en-us/library/ff972236(v=vs.85).aspx

**Comment by rogerhutchings** [comment]
I've written up a separate issue for this now, so I'll close this one.
