### ISSUE TITLE
Add ship collections

### ISSUE THREAD

**Issue by perry** [zooniverse/old-weather#8]
oldweather.org has the concept of "sources", which are essentially collections of ships, perhaps with extra metadata for a detail view.
- [ ] List view
- [ ] Detail view

**Comment by rogerhutchings** [comment]
Idea: create an additional subject set containing the extra metadata, and add a flag to prevent it from being loaded as an actual subject set

**Comment by rogerhutchings** [comment]
We're paring this right down for now, as we're starting off with a limited set anyway.

For future reference, we could just get all the sets and group them in the front end.
