### ISSUE TITLE
Random "Timeout" or "Hang" issues when loading new subject image (aka the Empty Subject Sets issue)

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/old-weather#82]
Problem:
- Occasionally, attempting to annotate any ship in Old Weather will cause a "timeout"/"hang" error - the loading sign keeps spinning with no images loaded.
- Occurs randomly, on multiple ships (e.g. Eastwind 1946, Northland 1930), on all browsers, regardless of signed in or not.

![zooniverse-oldweather-20151120-bug-report](https://cloud.githubusercontent.com/assets/13952701/11302595/42c51832-8f96-11e5-9d85-90b89f5dbd90.png)

Analysis:
- Calls to /api/subjects will randomly return empty subject sets.
- Empty subject sets results in the app "hanging", not knowing what to do.
- _It is unknown WHY /api/subjects is returning empty subject sets_, however.
- It is noted that if a user is logged in, the API remembers the "last served" subject sets (even empty ones), which will explain why logged in users can be "permanently locked out" of certain ships.

Notes:
- Tested on Surface Pro 3 Win 10 - Chrome 46 (primary), Edge 20, Opera 33, Firefox 42
- Tested with non-logged in user account to confirm random nature of empty subject sets.
- Tested with logged in user account to confirm logged-in users getting "locked out" of ships they were annotating.
- Sample record of notable attempts, with request headers & responses, attached.

[zooniverse-oldweather-20151120-bug-report.txt](https://github.com/zooniverse/old-weather/files/40163/zooniverse-oldweather-20151120-bug-report.txt)

**Comment by camallen** [comment]
pretty sure Roger debugged this that the default non-logged in queues weren't built due to the way we imported the data...

**Comment by rogerhutchings** [comment]
I did, and I edited the subject sets (tweaked set names and reverted), but it looks like it's still an issue

**Comment by camallen** [comment]
did the names actually save?

**Comment by rogerhutchings** [comment]
yeah

**Comment by camallen** [comment]
then it should have redone the q's, https://github.com/zooniverse/Panoptes/blob/69a96b3d4144adf9d162caab07169740b35a5e70/app/controllers/api/v1/subject_sets_controller.rb#L15

**Comment by camallen** [comment]
Is your workflow grouped? If not then it won't....

**Comment by rogerhutchings** [comment]
Not as far as I know, it's just grabbing subjects from a set

**Comment by camallen** [comment]
your workflow has to be grouped if you're using subject set groups. same as annotate..without this the grouping configs don't work.

**Comment by rogerhutchings** [comment]
They're not groups of sets, just sets

**Comment by camallen** [comment]
ok - each subject set is considered a group for selection. annotate works this way, check the grouped setting on the workflow. if you want grouped (subject_set) selection to work correctly (including building the non-logged in queues) this has to be set.

**Comment by rogerhutchings** [comment]
Okay - I've set this, and and edited the sets again, but I'm still getting empty sets. Would you mind having a look @camallen?

**Comment by shaunanoordin** [comment]
Please let me know if I can help look into the sets or etc - I'm currently running some tests to see the % of getting an empty set in each of the ships, just in case that data might help the debug.

**Comment by shaunanoordin** [comment]
Update: whatever's been happening in the past 10 minutes, the subject sets have gone from empty 80% of the time to the full 20 randomly-picked subjects in a set, all the time.

Tested for Eastwind 1946. (https://panoptes.zooniverse.org/api/subjects?sort=queued&workflow_id=886&page=1&page_size=20&subject_set_id=2529) Nice!

**Comment by camallen** [comment]
not sure what's up here..probably won't have time to look today..when is it needed?

**Comment by camallen** [comment]
please close if this isn't an issue anymore

**Comment by rogerhutchings** [comment]
Okay, I've checked all of the sets - they seem to be okay, apart from Bear 1899 (subject set id `2493`). Doesn't need to be today, but can you take a look on Monday?

**Comment by rogerhutchings** [comment]
I take it back, I think it's okay :D Thanks all
