### ISSUE TITLE
link to profile page in FAQ is broken

### ISSUE THREAD

**Issue by weedySeaDragon** [zooniverse/old-weather#86]
The FAQ page has a question "What happens if I make a mistake?" and the answer says "Head over to your [profile page](http://www.oldweather.org/profile) and ..."  but the link to the profile page is wrong.  When clicking on the 'profile page' link, a 404 is returned.  Here's what is displayed after I click on it:

 **404 Not Found**

```
Code: NoSuchKey
Message: The specified key does not exist.
Key: www.oldweather.org/profile
RequestId: 517F04A563B7179F
HostId: xUQed/T1H6JLn1TNgv3JW7KrVkcgZXkkg18gv43HuhD5igqWuWFc5Zu5jKpVBPfPvgXq4NamROY=
```

(In addition, the user name displayed in the upper-right-hand corner (in the header) is not a link, so there is no way that a user can access their profile.)

**Comment by rogerhutchings** [comment]
Thanks for logging this. I think this is referring to a feature that was descoped, so I've removed the reference to it via 5b75d33a90efd75a2d55b63a4c1bc0259646aa51.
