### ISSUE TITLE
Wildcam Gorongosa listed twice in the bottom navigation menu on oldweather.org

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/old-weather#88]
<img width="1086" alt="screen shot 2016-02-13 at 11 59 06 pm" src="https://cloud.githubusercontent.com/assets/753325/13028580/32a14b82-d2ae-11e5-8183-163d805f2ef6.png">

**Comment by yogaraptor** [comment]
The footer is built from https://static.zooniverse.org/zoo-footer/zoo-footer.json, which contains the duplicate record. Will see who I need to talk to about fixing that.

**Comment by yogaraptor** [comment]
Redeployed [zooniverse/zoo-footer](https://github.com/zooniverse/zoo-footer), fixed.
