### ISSUE TITLE
Bower not in requirements?

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/old-weather#89]
I had to manually `npm install bower` before I could run `make install`.

**Comment by rogerhutchings** [comment]
Bower is usually installed as a global requirement, but as we usually don't use it I've added a note in the README via 5a9e4978b8e5ec60dede55024cd57ebf6f079bac

The other thing we could do is install bower as a devDependency, then run `bower install` as a `postInstall` script in npm; it makes adding other packages via bower more difficult, as you'd have to run it locally each time through `node_modules/.bin/bower`, but that probably won't come up given the project isn't in development.
