### ISSUE TITLE
Remove Zooniverse branding

### ISSUE THREAD

**Issue by philip-brohan** [zooniverse/old-weather#97]
All the generic Zooniverse branding on the site should be removed (make it more like the whaling or classic sites).
The Twitter and Facebook links can remain, but they should link to oW twitter and Facebook pages.

The current oW home page is about 55% oldWeather and 45% advertisements for Zooniverse and other projects. The situation on workflow pages can be even worse - a workflow page before the log image has loaded, or if there's no image (transcription on a ship with nothing to transcribe, for instance) more than 90% of the screen space is adverts for other projects.
This is not good design, it does not help immersion in the project, and it prevents non-Zooniverse partners in the project from claiming any ownership (so we can't market it).

**Comment by saschaishikawa** [comment]
PR #99 doesn't address the issue directly (the "branding" is still there, it's just pushed down), but it's an improvement. Any thoughts, comments? @rogerhutchings, @itsravenous

**Comment by yogaraptor** [comment]
This certainly solves what I perceive as the problem - I guess @philip-brohan may want to weigh in?
